steps:
  # Install dependencies
  - name: node:18
    entrypoint: npm
    args: ["install"]

  # Build the Vite app
  - name: node:18
    entrypoint: npm
    args: ["run", "build"]

  # Build the container image
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "$_IMAGE", "."]

  # Push the container image
  - name: gcr.io/cloud-builders/docker
    args: ["push", "$_IMAGE"]

images:
  - "$_IMAGE"

substitutions:
  _IMAGE: "europe-west1-docker.pkg.dev/prime-bonbon-480612-p7/dream-green-repo/frontend"



  