steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/prime-bonbon-480612-p7/dream-green-frontend
      - .

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - gcr.io/prime-bonbon-480612-p7/dream-green-frontend

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - run
      - deploy
      - dream-green-frontend
      - --image
      - gcr.io/prime-bonbon-480612-p7/dream-green-frontend
      - --region
      - europe-west1
      - --platform
      - managed
      - --allow-unauthenticated

images:
  - gcr.io/prime-bonbon-480612-p7/dream-green-frontendsteps


  